# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611af188c05bd2411ffa3ab1bb2ec94fa93f7ceb4d3424ab7ca615fea9b52377785a8f2595590bf266877a631b48964f6fb3c69cb7b36a0a5f951c5d7531a9a8

test:
  secret_key_base: 6f6210d13b15ebdd63107d0cfb535298b752ade82862d09c0d25d6878e57c60d212b9b50e37acbc2c10f50eacaac6c4a2d17bfa1a1713eff5fdb94a036654fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
